In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [6]:
# save a file
x = torch.arange(4)
torch.save(x, 'x-file')
y = torch.zeros(4)
torch.save([x, y],'x-files')
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')

In [7]:
# load a file
x2 = torch.load('x-file')
print(x2)
x2, y2 = torch.load('x-files')
print((x2, y2))
mydict2 = torch.load('mydict')
print(mydict2)

tensor([0, 1, 2, 3])
(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))
{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}


In [8]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [10]:
# save model parameters to file
# state dictioanry is a dictionary object that maps each layer to its parameter tensor
torch.save(net.state_dict(), 'mlp.params')

In [13]:
# load model parameters from file
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval() # set the evluation mode, it will also return the state dictionary

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [14]:
Y_clone = clone(X)
Y_clone == Y # verify that they are the same

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])