In [3]:
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [4]:
# check if CUDA is available
torch.cuda.device_count()

4

In [5]:
# try if specific GPU is available, then return it / else return CPU
def try_gpu(i=0):
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')
# try if all GPUs are available, then return them
def try_all_gpus():
    devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0),
  device(type='cuda', index=1),
  device(type='cuda', index=2),
  device(type='cuda', index=3)])

In [7]:
x = torch.tensor([1, 2, 3])
print(x.device)
X = torch.ones(2, 3, device=try_gpu())
print(X)
Y = torch.rand(2, 3, device=try_gpu(1))
print(Y)

cpu
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[0.5638, 0.9668, 0.0087],
        [0.7495, 0.2989, 0.3932]], device='cuda:1')


In [10]:
# note that we need to move the data to the same GPU for computation
Z = X.cuda(1)
print(X)
print(Z)
print(Y + Z)
# if the data is already in the specific GPU, then it would not create new memory
Z.cuda(1) is Z

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:1')
tensor([[1.5638, 1.9668, 1.0087],
        [1.7495, 1.2989, 1.3932]], device='cuda:1')


True

In [11]:
# you can also save the model to a specific GPU
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

In [23]:
# net(Z) cannot be called because the data is not in the same GPU as the model
net(X)
net[0].weight.data.device

device(type='cuda', index=0)